### PR TITLE
Update Maven/Wrapper/Develocity Versions for better Compatibility

### PR DESCRIPTION
**Pull request by lasteris**
These changes solves quarkusio/quarkus#42756.

What i have done to check ?

1) Made commit changes.
2) ./mvnw clean install (quarkus-project-develocity-extension, 1.1.6-SNAPSHOT to make it visible via local m2) 3) Made some changes to https://github.com/quarkusio/quarkus/blob/main/.mvn/extensions.xml, which is now looking as below:

```
 <extensions>
    <extension>
        <groupId>com.gradle</groupId>
        <artifactId>develocity-maven-extension</artifactId>
        <version>1.22.2</version>
    </extension>
    <extension>
        <groupId>com.gradle</groupId>
        <artifactId>common-custom-user-data-maven-extension</artifactId>
        <version>2.0.1</version>
    </extension>
    <extension>
        <groupId>com.gradle</groupId>
        <artifactId>quarkus-build-caching-extension</artifactId>
        <version>1.8</version>
    </extension>
    <extension>
        <groupId>io.quarkus.develocity</groupId>
        <artifactId>quarkus-project-develocity-extension</artifactId>
        <version>1.1.6-SNAPSHOT</version>
    </extension>
</extensions>
```
4) cd into quarkus project git repository root directory on my disk drive 5) ./mvnw -Dquickly

Result looks like that:

```
...

[INFO] Quarkus - Documentation ............................ SUCCESS [ 10.929 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35:00 min
[INFO] Finished at: 2024-10-09T17:33:10+03:00
[INFO] ------------------------------------------------------------------------
[INFO] 14725 goals, 14709 executed, 16 from cache
```

This is only way how i finally successfully built Quarkus on my Windows machine via Maven Wrapper or even locally installed Maven of version 3.9.9

### CODE REVIEW

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Thanks. Not sure what's going on as I would have expected Maven to enforce the versions but if it works for you, let's merge it.

Thanks for digging and providing the fix!

**Comment by gsmet** [comment]
I released a new version. Dependabot should take care of the update tonight.

**Comment by lasteris** [comment]
> Thanks. Not sure what's going on as I would have expected Maven to enforce the versions but if it works for you, let's merge it.
> 
> Thanks for digging and providing the fix!

I think the main job is done via Develocity version update😉

**Comment by jprinet** [comment]
Could you actually run the build twice @lasteris and check that a build cache hit happens instead of the previous error?

**Comment by lasteris** [comment]
> Could you actually run the build twice @lasteris and check that a build cache hit happens instead of the previous error?

I can do clean and build sequencelly

**Comment by lasteris** [comment]
> > Could you actually run the build twice @lasteris and check that a build cache hit happens instead of the previous error?
> 
> I can do clean and build twice sequencelly

**Comment by lasteris** [comment]
@jprinet 
```
[INFO] -----------< io.quarkus:quarkus-kubernetes-service-binding >------------
[INFO] Building Quarkus - Kubernetes Service Binding - Runtime 999-SNAPSHOT [221/1230]
[INFO]   from extensions\kubernetes-service-binding\runtime\pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- clean:3.2.0:clean (clean-cache-dirs) @ quarkus-kubernetes-service-binding ---
[INFO] Deleting C:\Users\asus\repo\quarkus\extensions\kubernetes-service-binding\runtime\target
[INFO] Deleting C:\Users\asus\repo\quarkus\extensions\kubernetes-service-binding\runtime\.cache (includes = [], excludes = [])
[INFO]
[INFO] --- clean:3.2.0:clean (default-clean) @ quarkus-kubernetes-service-binding ---
[INFO] 
[INFO] --- buildnumber:3.0.0:create (get-scm-revision) @ quarkus-kubernetes-service-binding ---
[INFO]
[INFO] --- formatter:2.24.1:format (default) @ quarkus-kubernetes-service-binding ---
[INFO] Loaded from the build cache
[INFO]
[INFO] --- impsort:1.12.0:sort (sort-imports) @ quarkus-kubernetes-service-binding ---
[INFO] Loaded from the build cache, saving 0.004s
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ quarkus-kubernetes-service-binding ---
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO]
[INFO] --- quarkus-extension:999-SNAPSHOT:extension-descriptor (generate-extension-descriptor) @ quarkus-kubernetes-service-binding ---
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ quarkus-kubernetes-service-binding ---
[INFO] Loaded from the build cache, saving 0.413s
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ quarkus-kubernetes-service-binding ---
[INFO] Copying 11 resources from src\test\resources to target\test-classes
[INFO]
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ quarkus-kubernetes-service-binding ---
[INFO] Loaded from the build cache, saving 0.133s
[INFO]
[INFO] --- surefire:3.5.0:test (default-test) @ quarkus-kubernetes-service-binding ---
[INFO] Skipped
[INFO]
[INFO] --- jar:3.3.0:jar (default-jar) @ quarkus-kubernetes-service-binding ---
[INFO] Building jar: C:\Users\asus\repo\quarkus\extensions\kubernetes-service-binding\runtime\target\quarkus-kubernetes-service-binding-999-SNAPSHOT.jar
[INFO]
[INFO] --- source:3.2.1:jar-no-fork (attach-sources) @ quarkus-kubernetes-service-binding ---
[INFO] Building jar: C:\Users\asus\repo\quarkus\extensions\kubernetes-service-binding\runtime\target\quarkus-kubernetes-service-binding-999-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- install:3.1.1:install (default-install) @ quarkus-kubernetes-service-binding ---
[INFO] Installing C:\Users\asus\repo\quarkus\extensions\kubernetes-service-binding\runtime\pom.xml to C:\Users\asus\.m2\repository\io\quarkus\quarkus-kubernetes-service-binding\999-SNAPSHOT\quarkus-kubernetes-service-binding-999-SNAPSHOT.pom
[INFO] Installing C:\Users\asus\repo\quarkus\extensions\kubernetes-service-binding\runtime\target\quarkus-kubernetes-service-binding-999-SNAPSHOT.jar to C:\Users\asus\.m2\repository\io\quarkus\quarkus-kubernetes-service-binding\999-SNAPSHOT\quarkus-kubernetes-service-binding-999-SNAPSHOT.jar
[INFO] Installing C:\Users\asus\repo\quarkus\extensions\kubernetes-service-binding\runtime\target\quarkus-kubernetes-service-binding-999-SNAPSHOT-sources.jar to C:\Users\asus\.m2\repository\io\quarkus\quarkus-kubernetes-service-binding\999-SNAPSHOT\quarkus-kubernetes-service-binding-999-SNAPSHOT-sources.jar

.....

[INFO] Quarkus - Kubernetes Service Binding - Deployment .. SUCCESS [  0.584 s]

....

[INFO] Quarkus - Kubernetes Service Binding - SPI ......... SUCCESS [  0.358 s]
```
result output per second build for problematic extension

**Comment by jprinet** [comment]
Great @lasteris and thanks for reporting back, looks like the local cache hit does not break the build, I am still expecting a full confirmation with a remote cache hit when the Quarkus build will have run with the upgraded extension.

**Comment by lasteris** [comment]
>  I am still expecting a full confirmation with a remote cache hit when the Quarkus build will have run with the upgraded extension.
 For remote cache, I need account to Develocity ?

**Comment by jprinet** [comment]
The remote cache will be populated by the CI workflow.
You will then be able to get remote cache hit.
See [this](https://docs.gradle.com/develocity/maven-build-cache/) for more details

**Pull request merged**
